import type { Skill } from "../engine/types";

export const SKILLS: Skill[] = [
  {
    id: "power-strike",
    name: "Power Strike",
    description: "A committed blow. Physical damage with extra force.",
    mpCost: 8,
    cooldown: 18,
    target: "enemy",
    effects: [{ type: "damage", damageType: "physical", power: 1.45 }],
  },
  {
    id: "bash",
    name: "Shield Bash",
    description: "Slam the foe. Chance to stun.",
    mpCost: 10,
    cooldown: 32,
    target: "enemy",
    effects: [
      { type: "damage", damageType: "physical", power: 0.9 },
      { type: "applyStatus", status: "stun", duration: 14, potency: 1, chance: 0.55 },
    ],
  },
  {
    id: "taunt",
    name: "Taunt",
    description: "Force attention. Enemies prefer this target.",
    mpCost: 6,
    cooldown: 40,
    target: "self",
    effects: [{ type: "applyStatus", status: "taunt", duration: 36, potency: 1, chance: 1 }],
  },
  {
    id: "shield-wall",
    name: "Shield Wall",
    description: "Raise a barrier and brace.",
    mpCost: 12,
    cooldown: 48,
    target: "self",
    effects: [{ type: "shield", amount: 55, statusId: "shielded" }],
  },
  {
    id: "poison-stab",
    name: "Venom Edge",
    description: "A cut that lingers.",
    mpCost: 9,
    cooldown: 22,
    target: "enemy",
    effects: [
      { type: "damage", damageType: "physical", power: 0.85 },
      { type: "applyStatus", status: "poison", duration: 48, potency: 9, chance: 0.9 },
    ],
  },
  {
    id: "backstab",
    name: "Backstab",
    description: "Punish the wounded. Extra damage below 40% HP.",
    mpCost: 12,
    cooldown: 28,
    target: "enemy",
    effects: [
      {
        type: "damage",
        damageType: "physical",
        power: 1.2,
        executeBonus: 0.7,
        executeBelowPct: 40,
      },
    ],
  },
  {
    id: "haste",
    name: "Fleetfoot",
    description: "Quicken the action gauge.",
    mpCost: 11,
    cooldown: 50,
    target: "ally",
    effects: [{ type: "applyStatus", status: "haste", duration: 40, potency: 1, chance: 1 }],
  },
  {
    id: "fireball",
    name: "Fireball",
    description: "A searing bolt. May ignite.",
    mpCost: 14,
    cooldown: 16,
    target: "enemy",
    effects: [
      { type: "damage", damageType: "magical", power: 1.5 },
      { type: "applyStatus", status: "burn", duration: 28, potency: 8, chance: 0.45 },
    ],
  },
  {
    id: "blizzard",
    name: "Blizzard",
    description: "Freeze the field. Hits all enemies and slows.",
    mpCost: 22,
    cooldown: 42,
    target: "allEnemies",
    effects: [
      { type: "damage", damageType: "magical", power: 1.05 },
      { type: "applyStatus", status: "slow", duration: 22, potency: 1, chance: 0.7 },
    ],
  },
  {
    id: "arcane-bolt",
    name: "Arcane Bolt",
    description: "Cheap, reliable magic.",
    mpCost: 6,
    cooldown: 8,
    target: "enemy",
    effects: [{ type: "damage", damageType: "magical", power: 1.05 }],
  },
  {
    id: "ignite",
    name: "Ignite",
    description: "Lock a burn onto a single foe.",
    mpCost: 10,
    cooldown: 26,
    target: "enemy",
    effects: [
      { type: "applyStatus", status: "burn", duration: 40, potency: 12, chance: 1 },
      { type: "damage", damageType: "magical", power: 0.4 },
    ],
  },
  {
    id: "heal",
    name: "Mend",
    description: "Restore a wounded ally.",
    mpCost: 12,
    cooldown: 14,
    target: "ally",
    effects: [{ type: "heal", power: 1.35 }],
  },
  {
    id: "mass-heal",
    name: "Circle of Mercy",
    description: "Heal the whole side.",
    mpCost: 24,
    cooldown: 50,
    target: "allAllies",
    effects: [{ type: "heal", power: 0.85 }],
  },
  {
    id: "bless",
    name: "Bless",
    description: "Grant might to an ally.",
    mpCost: 10,
    cooldown: 36,
    target: "ally",
    effects: [{ type: "applyStatus", status: "atkUp", duration: 40, potency: 25, chance: 1 }],
  },
  {
    id: "cleanse",
    name: "Cleanse",
    description: "Strip harmful statuses.",
    mpCost: 8,
    cooldown: 20,
    target: "ally",
    effects: [{ type: "cleanse" }],
  },
  {
    id: "regenerate",
    name: "Regenerate",
    description: "A lingering salve.",
    mpCost: 11,
    cooldown: 34,
    target: "ally",
    effects: [{ type: "applyStatus", status: "regen", duration: 40, potency: 10, chance: 1 }],
  },
  {
    id: "aimed-shot",
    name: "Aimed Shot",
    description: "Precise physical damage.",
    mpCost: 9,
    cooldown: 16,
    target: "enemy",
    effects: [{ type: "damage", damageType: "physical", power: 1.35 }],
  },
  {
    id: "pin-down",
    name: "Pin Down",
    description: "Slow the target and chip health.",
    mpCost: 8,
    cooldown: 28,
    target: "enemy",
    effects: [
      { type: "damage", damageType: "physical", power: 0.7 },
      { type: "applyStatus", status: "slow", duration: 30, potency: 1, chance: 0.85 },
    ],
  },
  {
    id: "execute",
    name: "Execute",
    description: "Finish the weak. Massive bonus below 35% HP.",
    mpCost: 14,
    cooldown: 24,
    target: "enemy",
    effects: [
      {
        type: "damage",
        damageType: "physical",
        power: 1.1,
        executeBonus: 1.1,
        executeBelowPct: 35,
      },
    ],
  },
  {
    id: "rage",
    name: "Bloodrage",
    description: "Might up, armor down. Reckless.",
    mpCost: 8,
    cooldown: 44,
    target: "self",
    effects: [
      { type: "applyStatus", status: "atkUp", duration: 36, potency: 40, chance: 1 },
      { type: "applyStatus", status: "defDown", duration: 36, potency: 25, chance: 1 },
    ],
  },
  {
    id: "cleave",
    name: "Cleave",
    description: "Sweep all enemies.",
    mpCost: 16,
    cooldown: 30,
    target: "allEnemies",
    effects: [{ type: "damage", damageType: "physical", power: 0.95 }],
  },
  {
    id: "shatter",
    name: "Armor Break",
    description: "Lower the foe's defense.",
    mpCost: 9,
    cooldown: 32,
    target: "enemy",
    effects: [
      { type: "damage", damageType: "physical", power: 0.75 },
      { type: "applyStatus", status: "defDown", duration: 32, potency: 30, chance: 1 },
    ],
  },
  {
    id: "potion",
    name: "Potion",
    description: "A flask of red. Restores HP.",
    mpCost: 0,
    cooldown: 0,
    target: "self",
    effects: [{ type: "heal", power: 1.1 }],
  },
  {
    id: "ether",
    name: "Ether",
    description: "Restores MP.",
    mpCost: 0,
    cooldown: 0,
    target: "self",
    effects: [{ type: "restoreMp", amount: 40 }],
  },
  {
    id: "share-ether",
    name: "Share Ether",
    description: "Restore an ally's MP.",
    mpCost: 0,
    cooldown: 0,
    target: "ally",
    effects: [{ type: "restoreMp", amount: 40 }],
  },
];
